### ISSUE TITLE
Remove contrib

### ISSUE THREAD

**Issue by 0x00B1** [CellProfiler/CellProfiler#1492]
- [ ] [Remove ./contrib/include](https://github.com/CellProfiler/CellProfiler/issues/1473)
- [ ] [Replace contrib.english with inflection](https://github.com/CellProfiler/CellProfiler/issues/1437)
- [ ] [Use objgraph from PyPI ](https://github.com/CellProfiler/CellProfiler/issues/1438)

**Comment by 0x00B1** [comment]
Completed
